[][Fix pointer type casting warning of proprietary mdio ioctl]
[Description]
Fix pointer type casting warning of proprietary mdio ioctl.
Change to use implicit type casting to avoid potential endianness
problem.

drivers/net/ethernet/mediatek/mtk_eth_dbg.c:427:7: error: passing
argument 5 of 'mii_mgr_read_cl45' from incompatible pointer type
[-Werror=incompatible-pointer-types]
       &mii.val_out);
       ^~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:387:87: note: expected
'u16 *' {aka 'short unsigned int *'} but argument is of type
'unsigned int *' static void mii_mgr_read_cl45(struct mtk_eth
*eth, u16 port, u16 devad, u16 reg, u16 *data)
                                    ~~~~~^~~~

[Release-log]
N/A

Change-Id: I172b995f1279ca561acb857fa3b47683545000f1
Reviewed-on: https://gerrit.mediatek.inc/c/openwrt/feeds/mtk_openwrt_feeds/+/4577257